# 1주차 미션

## Q1
- 여러분은 파이썬을 통해 설문조사 문항의 응답내역을 분석하게 되었습니다. 문항별 응답내용에는 하나의 응답만 할 수 있는 single choice 문제와 여러 응답을 선택할 수 있는 multiple choice 문제가 있습니다. 2개를 구분하기 위해 single choice 문항 번호에 "_"를 표기하지 않기로 했습니다.

- 문항별 응답내역이 'question'에 담겨 있을 때, 조건문과 반복문을 사용하여 아래와 같은 결과가 출력되도록 코드를 작성해보세요.

In [2]:
question = ['Q2', 'Q3', 'Q4', 'Q5', 'Q6_1', 'Q6_2', 'Q6_3', 'Q6_4', 'Q6_5', 'Q6_6',
       'Q6_7', 'Q6_8', 'Q6_9', 'Q6_10', 'Q6_11', 'Q6_12', 'Q7_1', 'Q7_2',
       'Q7_3', 'Q7_4', 'Q7_5', 'Q7_6', 'Q7_7', 'Q8', 'Q9', 'Q10_1', 'Q10_2',
       'Q10_3']

In [3]:
result = []
for i in question:
    if not '_' in i: # _가 없는 원소만 result에 추가
        result.append(i)

In [4]:
result

['Q2', 'Q3', 'Q4', 'Q5', 'Q8', 'Q9']

## Q2
- 한스 로슬링(Hans Rosling, 1948년 7월 27일 ~ 2017년 2월 7일)은 스웨덴의 의사이자 통계학자로 비영리 벤처 갭마인더 재단의 공동설립자이기도 합니다. 빅데이터를 가장 잘 활용하는 보건 통계학자로 알려져 있습니다. 베스트셀러 책인 "팩트풀니스" 저자이기도 합니다. 갭마인더 사이트에서는 연도별, 국가별 GDP와 기대수명 데이터를 제공하고 있는데, 대표적으로 파이썬 라이브러리 중 'seaborn'에서 제공되는 예제 데이터가 있습니다. 오늘은 이 데이터를 활용해 문제를 풀어보겠습니다.

- 다음의 데이터는 연도, 국가별 기대수명을 나타내고 있는 데이터 입니다. 2011년 부터의 연도별, 국가별 평균 기대수명을 구해주세요. (2011년도 포함되게 구합니다.)

- [필수 조건] groupby 나 pivot_table을 활용합니다. groupby 로 구할 때 unstack()이라는 기능을 사용하여 아래와 같이 컬럼에 인덱스 값을 올려서 표기할 수 있습니다.
만약 행에는 '연도'가, 열에 '국가'가 들어있고 수치 데이터의 결과값이 아래와 같다면, 출력형태는 조금 달라도 괜찮습니다.

In [5]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/mwaskom/seaborn-data/master/healthexp.csv")
df

     Year        Country  Spending_USD  Life_Expectancy
0    1970        Germany       252.311             70.6
1    1970         France       192.143             72.2
2    1970  Great Britain       123.993             71.9
3    1970          Japan       150.437             72.0
4    1970            USA       326.961             70.9
..    ...            ...           ...              ...
269  2020        Germany      6938.983             81.1
270  2020         France      5468.418             82.3
271  2020  Great Britain      5018.700             80.4
272  2020          Japan      4665.641             84.7
273  2020            USA     11859.179             77.0

[274 rows x 4 columns]

In [6]:
df_2011 = df[df['Year']>=2011].reset_index(drop=True)
pivot_df = pd.pivot_table(df_2011, index='Year', columns='Country',
                            values = 'Life_Expectancy')
pivot_df

Country  Canada  France  Germany  Great Britain  Japan   USA
Year
2011       81.4    82.3     80.5           81.0   82.7  78.7
2012       81.6    82.1     80.6           81.0   83.2  78.8
2013       81.7    82.3     80.6           81.1   83.4  78.8
2014       81.8    82.8     81.2           81.4   83.7  78.9
2015       81.9    82.4     80.7           81.0   83.9  78.7
2016       82.0    82.7     81.0           81.2   84.1  78.7
2017       81.9    82.7     81.1           81.3   84.2  78.6
2018       82.0    82.8     81.0           81.3   84.3  78.7
2019       82.2    82.9     81.3           81.4   84.4  78.8
2020       81.7    82.3     81.1           80.4   84.7  77.0

## Q3
-  Jupyter notebook 은 문서와 코드를 함께 작성할 수 있다는 점이 장점입니다. Jupyter notebook 에서 지원하는 Markdown 문법을 사용하여, 이번 주에 배운 내용을 정리해 보세요!

## Q4
- 앞으로 우리는 공공데이터포털에서 데이터를 다운로드 받아 과정을 진행할 예정입니다. 본격적인 학습 이전에! 데이터를 다루는 방법이 익숙해지도록 한번 더 연습해보고, 어떤 문제를 풀 수 있을지도 함께 고민해보아요!

In [7]:
df = pd.read_csv('./data/전국무인교통단속카메라표준데이터.csv', encoding = 'utf-8-sig')
df

,무인교통단속카메라관리번호,시도명,시군구명,도로종류,도로노선번호,도로노선명,도로노선방향,소재지도로명주소,소재지지번주소,위도,...,제한속도,단속구간위치구분,과속단속구간길이,보호구역구분,설치연도,관리기관명,관리기관전화번호,데이터기준일자,제공기관코드,제공기관명
0,F9486,경기도,시흥시,시도,해당없음,해송십리로,3.0,NaN,경기도 시흥시 정왕동 2566,37.362615,...,50,NaN,NaN,NaN,2016.0,경기도남부경찰청,031-888-3952,2021-10-13,1337000,경찰청 경기도남부경찰청
1,F9487,경기도,시흥시,시도,해당없음,해송십리로,3.0,NaN,경기도 시흥시 정왕동 2554,37.364819,...,50,NaN,NaN,NaN,2016.0,경기도남부경찰청,031-888-3952,2021-10-13,1337000,경찰청 경기도남부경찰청
2,F9488,경기도,안산시,일반국도,39번,중앙대로,3.0,NaN,경기도 안산시 단원구 고잔동 821,37.316295,...,60,NaN,NaN,NaN,2016.0,경기도남부경찰청,031-888-3952,2021-10-13,1337000,경찰청 경기도남부경찰청
3,F9489,경기도,안산시,시도,해당없음,해안로,3.0,NaN,경기도 안산시 상록구 사동 1636,37.297799,...,60,NaN,NaN,NaN,2016.0,경기도남부경찰청,031-888-3952,2021-10-13,1337000,경찰청 경기도남부경찰청
4,F9490,경기도,안성시,시도,해당없음,안성맞춤대로,3.0,NaN,경기도 안성시 미양면 양변리 260-2,36.952602,...,60,NaN,NaN,NaN,2016.0,경기도남부경찰청,031-888-3952,2021-10-13,1337000,경찰청 경기도남부경찰청
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32580,대천역 정문 앞,충청남도,보령시,일반국도,36,대해로,2.0,충청남도 보령시 대해로 116,충청남도 보령시 내항동 336-11,36.341618,...,0,NaN,NaN,NaN,2019.0,충청남도 보령시청,041-930-3973,2022-03-07,4510000,충청남도 보령시
32581,죽정동,충청남도,보령시,시도,NaN,지장골길,2.0,충청남도 보령시 지장골길 105,충청남도 보령시 죽정동 649-5,36.359853,...,0,NaN,NaN,NaN,2019.0,충청남도 보령시청,041-930-3973,2022-03-07,4510000,충청남도 보령시
32582,대관초등학교 후문,충청남도,보령시,시도,NaN,대관초등길,2.0,충청남도 보령시 대관초등길 100,충청남도 보령시 대천동 1482,36.356560,...,0,NaN,NaN,NaN,2019.0,충청남도 보령시청,041-930-3973,2022-03-07,4510000,충청남도 보령시
32583,대천초등학교 정문,충청남도,보령시,시도,NaN,대천로,2.0,충청남도 보령시 대천로 59,충청남도 보령시 대천동 614-40,36.354116,...,0,NaN,NaN,NaN,2021.0,충청남도 보령시청,041-930-3973,2022-03-07,4510000,충청남도 보령시
32584,동대초등학교 정문,충청남도,보령시,시도,NaN,한내로터리길,2.0,충청남도 보령시 한내로터리길 137-12,충청남도 보령시 동대동 349-6,36.352592,...,0,NaN,NaN,NaN,2021.0,충청남도 보령시청,041-930-3973,2022-03-07,4510000,충청남도 보령시